apiVersion: v1
kind: Service
metadata:
  name: internal-lb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: internal-lb
spec:
  type: LoadBalancer
  selector:
    app: rolling-deploy
  ports:
  - port: 8080
    targetPort: 8090
    protocol: TCP
