apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rolling-deploy
  name: rolling-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolling-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rolling-deploy
    spec:
      containers:
      - image: gcr.io/juyeon-pjt-347108/was-server:app-0.5
        name: was-server
        resources: {}
status: {}
